// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV4Wm3xmrqDEgLkwlzcQczA2Xer7ZHoh8',
    appId: '1:665639258138:web:0c3630b9254f4fb57029a3',
    messagingSenderId: '665639258138',
    projectId: 'aspay-91389',
    authDomain: 'aspay-91389.firebaseapp.com',
    storageBucket: 'aspay-91389.appspot.com',
    measurementId: 'G-GSC8BDN3YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHspWIV01yA88RzhqnJ5XMRljg0Y6Npao',
    appId: '1:665639258138:android:0c8ed9031cdc4ea47029a3',
    messagingSenderId: '665639258138',
    projectId: 'aspay-91389',
    storageBucket: 'aspay-91389.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtyzCcG14AVWIcpTWMNRfhG0Ik28zAQRo',
    appId: '1:665639258138:ios:d8248672327b841b7029a3',
    messagingSenderId: '665639258138',
    projectId: 'aspay-91389',
    storageBucket: 'aspay-91389.appspot.com',
    iosBundleId: 'com.example.googleMapInFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtyzCcG14AVWIcpTWMNRfhG0Ik28zAQRo',
    appId: '1:665639258138:ios:d8248672327b841b7029a3',
    messagingSenderId: '665639258138',
    projectId: 'aspay-91389',
    storageBucket: 'aspay-91389.appspot.com',
    iosBundleId: 'com.example.googleMapInFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV4Wm3xmrqDEgLkwlzcQczA2Xer7ZHoh8',
    appId: '1:665639258138:web:5dd020e4a610a1f77029a3',
    messagingSenderId: '665639258138',
    projectId: 'aspay-91389',
    authDomain: 'aspay-91389.firebaseapp.com',
    storageBucket: 'aspay-91389.appspot.com',
    measurementId: 'G-VXWE6S5MXJ',
  );

}